#!/usr/bin/env bash
# gen_vfs_offsets.sh — Extract VFS entry point offsets from the VFS ELF
#
# Reads symbol addresses from ppap_pcxt_vfs.elf and generates a C
# source file that initializes vfs_fptrs[] with the correct offsets.
# The segment field is left as 0 — patched at runtime by seg_init.
#
# Usage: ./scripts/gen_vfs_offsets.sh <vfs_elf> <output.c> [nm_binary]

set -euo pipefail

VFS_ELF="${1:?Usage: $0 <vfs_elf> <output.c> [nm_binary]}"
OUTPUT="${2:?Usage: $0 <vfs_elf> <output.c> [nm_binary]}"
NM="${3:-ia16-elf-nm}"

# Entry point symbols in the order matching vfs_fptrs[] indices
ENTRIES=(
  vfs_init_entry
  vfs_mount_entry
  vfs_umount_entry
  vfs_lookup_entry
  vfs_lookup_flags_entry
  vfs_lookup_parent_entry
  vfs_path_normalize_entry
  vfs_find_mount_entry
  vfs_alloc_vnode_entry
  vfs_ref_vnode_entry
  vfs_rel_vnode_entry
)

# Also extract core entry points (for core_fptrs[] in VFS)
CORE_ENTRIES=(
  klog_entry
  klogf_entry
  kmem_pool_init_entry
  kmem_alloc_entry
  kmem_free_entry
  kmem_free_count_entry
)

cat > "$OUTPUT" << 'HEADER'
/* Auto-generated by gen_vfs_offsets.sh — do not edit */
#ifdef __ia16__
#include <stdint.h>

HEADER

# Extract VFS entry offsets
echo "const uint16_t vfs_entry_offsets[] = {" >> "$OUTPUT"
for sym in "${ENTRIES[@]}"; do
  addr=$("$NM" "$VFS_ELF" 2>/dev/null | awk -v s="$sym" '$3 == s {print "0x" $1}')
  if [[ -z "$addr" ]]; then
    echo "  0x0000,  /* $sym — NOT FOUND */" >> "$OUTPUT"
  else
    echo "  $addr,  /* $sym */" >> "$OUTPUT"
  fi
done
echo "};" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "#endif /* __ia16__ */" >> "$OUTPUT"
