#!/usr/bin/env python3
"""
bdf2c.py — Convert a BDF font file to a C array source file.

Reads a BDF (Bitmap Distribution Format) font and emits a C source file
containing a const uint8_t array of glyph bitmaps for codepoints 0–255.

Usage:
    python3 bdf2c.py --input FONT.bdf --output font.c \
                     --name font8x16 --width 8 --height 16
"""

import argparse
import sys


def parse_bdf(path):
    """Parse a BDF file and return a dict of {encoding: [bitmap_rows]}."""
    glyphs = {}
    encoding = None
    bbox_h = 0
    bbox_yoff = 0
    in_bitmap = False
    rows = []

    with open(path, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith('ENCODING '):
                encoding = int(line.split()[1])
            elif line.startswith('BBX '):
                parts = line.split()
                bbox_h = int(parts[2])
                bbox_yoff = int(parts[4])
            elif line == 'BITMAP':
                in_bitmap = True
                rows = []
            elif line == 'ENDCHAR':
                if in_bitmap and encoding is not None and 0 <= encoding <= 0xFFFF:
                    glyphs[encoding] = (rows, bbox_h, bbox_yoff)
                in_bitmap = False
                encoding = None
            elif in_bitmap:
                rows.append(int(line, 16))

    return glyphs


def make_glyph(glyphs, cp, target_w, target_h):
    """Extract and pad/crop a glyph to the target dimensions.

    Returns a list of target_h byte values, one per row.
    """
    if cp not in glyphs:
        # Missing glyph: solid rectangle as placeholder
        if target_w <= 8:
            fill = (0xFF >> (8 - target_w)) << (8 - target_w)
        else:
            fill = 0xFF
        return [fill] * target_h

    rows, bbox_h, bbox_yoff = glyphs[cp]

    # Pad to target height by centering with top bias.
    # BDF bbox_yoff is the offset from the baseline (negative = descender).
    # For our simple case: pad top and bottom to reach target_h.
    if len(rows) < target_h:
        pad_total = target_h - len(rows)
        pad_top = pad_total // 2
        pad_bottom = pad_total - pad_top
        rows = [0] * pad_top + rows + [0] * pad_bottom
    elif len(rows) > target_h:
        rows = rows[:target_h]

    # Mask to target width (top bits)
    if target_w < 8:
        mask = (0xFF >> (8 - target_w)) << (8 - target_w)
        rows = [r & mask for r in rows]

    return rows


def emit_c(glyphs, name, target_w, target_h, output_path):
    """Generate the C source file."""
    with open(output_path, 'w') as f:
        f.write('/* Auto-generated by bdf2c.py — do not edit */\n')
        f.write('#include <stdint.h>\n\n')
        f.write(f'const uint8_t {name}[256][{target_h}] = {{\n')

        for cp in range(256):
            rows = make_glyph(glyphs, cp, target_w, target_h)
            hex_str = ', '.join(f'0x{b:02X}' for b in rows)
            label = ''
            if 0x20 <= cp <= 0x7E:
                ch = chr(cp)
                if ch == '\\':
                    label = "  /* '\\\\' */"
                elif ch == "'":
                    label = "  /* '\\'' */"
                else:
                    label = f"  /* '{ch}' */"
            elif cp < 0x20:
                label = f'  /* 0x{cp:02X} */'
            f.write(f'    {{ {hex_str} }},{label}\n')

        f.write('};\n')


def main():
    parser = argparse.ArgumentParser(description='Convert BDF font to C array')
    parser.add_argument('--input', required=True, help='Input BDF file')
    parser.add_argument('--output', required=True, help='Output C file')
    parser.add_argument('--name', required=True, help='Array name')
    parser.add_argument('--width', type=int, required=True, help='Target glyph width')
    parser.add_argument('--height', type=int, required=True, help='Target glyph height')
    args = parser.parse_args()

    glyphs = parse_bdf(args.input)
    if not glyphs:
        print(f'Error: no glyphs found in {args.input}', file=sys.stderr)
        sys.exit(1)

    emit_c(glyphs, args.name, args.width, args.height, args.output)
    count = sum(1 for cp in range(256) if cp in glyphs)
    print(f'bdf2c: {count}/256 glyphs from {args.input} -> {args.output}')


if __name__ == '__main__':
    main()
